/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t amiga_fnt[];
extern const uint8_t amiga_fnt_end[];
#if __cplusplus >= 201103L
static constexpr size_t amiga_fnt_size=2048;
#else
static const size_t amiga_fnt_size=2048;
#endif
